# Copyright (C) 2026, Nicolas Scalese
# Licensed under the GNU GPL v3 or later. Info:  https://www.gnu.org/licenses/gpl-3.0.html


# --- HYPRPAPER configuration file ---

# Disable the mascot splash screen
splash = false

# Enable IPC for the script
ipc = on
